services:
  bff:
    build: ./bff
    volumes:
      - ./bff:/app
      - ./userservice:/userservice
    ports:
      - "8080:8080"
    command: air

  userservice:
    build: ./userservice
    ports:
      - "50052:50052"
    volumes:
      - ./userservice:/app
    command: air
  # db:
  #   image: mysql:latest
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: bnn
  #   volumes:
  #     - ./data:/var/lib/mysql
